name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.6', '3.7', '3.8', '3.9', '3.10', 'pypy3']
        architecture: [x86, x64]
        exclude:
          - os: ubuntu-latest
            architecture: x86
          - os: macos-latest
            architecture: x86
          - os: windows-latest
            python: pypy3
          - os: windows-latest
            python: '3.6'
          - os: macos-latest
            python: pypy3
          - os: macos-latest
            python: '3.6'

    name: ${{ matrix.os }} Py ${{ matrix.python }} ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.architecture }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip setuptools poetry
          poetry update

      - name: Run pre-commit
        if: "!startsWith(matrix.python, 'pypy')"
        run: |
          python -m pip install pre-commit
          pre-commit run --all-files

      - name: Run unit tests
        run: poetry run pytest

  build:
    #needs: test
    runs-on: ubuntu-latest
    name: Build Python source .tar.gz

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Build source package
        run: |
          python -m pip install --upgrade pip setuptools poetry
          poetry build

      - name: Upload source package
        uses: actions/upload-artifact@v1
        with:
          name: fido2-python-sdist
          path: dist
